/**
 * @description       :  An apex page controller that takes the user to the right start page based on credentials or lack thereof
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 11-20-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   11-20-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
 **/
@IsTest
public with sharing class CommunitiesSelfRegConfirmControllerTest {
  @IsTest
  public static void testCommunitiesSelfRegConfirmController(){
    // Instantiate a new controller with all parameters in the page
    CommunitiesSelfRegConfirmController controller = new CommunitiesSelfRegConfirmController();
  }
}