/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 11-01-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   11-01-2021   Samuel SIrkis                        Initial Version
 **/
public enum OlosEventNames {
    INSERT_CAMPAIGN_SF_TO_OLOS,
    UPDATE_CAMPAIGN_SF_TO_OLOS,
    INSERT_CAMPAIGN_MEMBER_SF_TO_OLOS,
    DELETE_CAMPAIGN_MEMBER_SF_TO_OLOS,
    UPDATE_CAMPAIGN_MEMBER_SF_TO_OLOS,
    INSERT_USER_SF_TO_OLOS,
    UPDATE_USER_SF_TO_OLOS
}